
# Credenciales  para usuarios de Sauce Demo
standard_user.password=secret_sauce
problem_user.password=secret_sauce
performance_glitch_user.password=secret_sauce
locked_out_user.password=secret_sauce


